### ISSUE TITLE
Great Project! Can I have a breadboard version?

### ISSUE THREAD

**Issue by panelresources** [rscott2049/DECstation2040#1]
Hi, this project is great! I appreciate your efforts and I love retro workstations.
However, soldering the RP2040 and the BGA HyperRAM is challenging.

Is it possible to use one or more 8-pin 3.3V PSRAM that used in ESP32 modules instead of the HyperRAM? So, that the level shifters can be deleted. Then, we can use off-the-shelf Raspberry Pi Pico or Pico W for the build on a breadboard.

**Comment by Anathae** [comment]
The chip that is being used here is a self refreshing dram chip that can runs at 1.8v.  Looks like the 8 pin PSRAM chips are limited to 8MB.  Replacing one BGA chip to 4 eight pin SOP chips would be a significant change in the circuit board.  As the HyperRAM interface (HyperBUS) is an eight pin bidirectional command and data bus, and PSRAM is QSPI, there would also be a significant change in the underlying code.  This would be a different project, IMNSHO.  Perhaps DECstationPiPico.

**Comment by rscott2049** [comment]
Anathae has it right - the QPSI PSRAMs aren't fast enough, and would require much different code Note that Dmitry's project does use PSRAMs, so you may want to start there. Should be pretty easy to swap out the HyperRAM specific code for Dmitry's
PSRAM code, and use a RaspiPico board. I don't think there'll be enough bandwidth for video, however.

**Comment by panelresources** [comment]
Thank you very much Anathae and Rscott2049 for the explanation.
