### ISSUE TITLE
Missing rev 2.1 running photo

### ISSUE THREAD

**Issue by ironhaven** [rscott2049/DECstation2040#2]
The photo in the README labeled "rev 2.1 running" is the same photo as "rev 1.5 running". Can you update the photo so show the latest revision hooked up and running?

**Comment by rscott2049** [comment]
Thanks for pointing that out! Cut'n'paste error - there was a photo in the doc/photos directory, but the README didn't point to it. I took a new photo (better quality, and shows the Logitech keyboard in action), and fixed the README.
